/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author angel
 */
public class ventanaInicioUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ventanaInicioUsuario
     */
    public ventanaInicioUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        solicitarBtn = new javax.swing.JButton();
        cerrarBtn = new javax.swing.JButton();
        notificacionBtn = new javax.swing.JButton();
        viaticoBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setLayout(null);

        solicitarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Solicitudes.png"))); // NOI18N
        solicitarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitarBtnActionPerformed(evt);
            }
        });
        menu.add(solicitarBtn);
        solicitarBtn.setBounds(10, 370, 190, 70);

        cerrarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar Sesión.png"))); // NOI18N
        cerrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarBtnActionPerformed(evt);
            }
        });
        menu.add(cerrarBtn);
        cerrarBtn.setBounds(210, 450, 190, 70);

        notificacionBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Notificaciones.png"))); // NOI18N
        notificacionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificacionBtnActionPerformed(evt);
            }
        });
        menu.add(notificacionBtn);
        notificacionBtn.setBounds(210, 370, 190, 70);

        viaticoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Viáticos.png"))); // NOI18N
        viaticoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viaticoBtnActionPerformed(evt);
            }
        });
        menu.add(viaticoBtn);
        viaticoBtn.setBounds(10, 450, 190, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BackgroundLogin.jpg"))); // NOI18N
        menu.add(jLabel1);
        jLabel1.setBounds(0, 0, 410, 560);

        getContentPane().add(menu);
        menu.setBounds(0, -1, 410, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void solicitarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitarBtnActionPerformed
        new ventanaSolicitar().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_solicitarBtnActionPerformed

    private void notificacionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificacionBtnActionPerformed
        new ventanaNotificaciones().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_notificacionBtnActionPerformed

    private void viaticoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viaticoBtnActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_viaticoBtnActionPerformed

    private void cerrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarBtnActionPerformed
        new loginWindow().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaInicioUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaInicioUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaInicioUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaInicioUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaInicioUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel menu;
    private javax.swing.JButton notificacionBtn;
    private javax.swing.JButton solicitarBtn;
    private javax.swing.JButton viaticoBtn;
    // End of variables declaration//GEN-END:variables
}
