
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author angel
 */
public class ventanaInventario extends javax.swing.JFrame {
    boolean validacion = true;
    conexion con;
    DefaultTableModel modelo;
    private String accion, id_actualizar,sql,mensaje;
    /**
     * Creates new form ventanaInventario
     */
    public ventanaInventario() {
        initComponents();
        this.setTitle("Inventario");
        panelAlta.setVisible(false);
        panelModificar.setVisible(false);
        this.setLocationRelativeTo(null);
        primeraCarga();
        modificarBtn.setEnabled(false);
        accion = "Insertar";
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraLatera = new javax.swing.JPanel();
        modificarBtn = new javax.swing.JButton();
        darDeBajaBtn = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        atrasBtn = new javax.swing.JButton();
        darDeAltaBtn = new javax.swing.JButton();
        inventarioBtn = new javax.swing.JButton();
        areaAcción = new javax.swing.JPanel();
        panelAlta = new javax.swing.JPanel();
        idAltaField = new javax.swing.JTextField();
        ID = new javax.swing.JLabel();
        numeralAltaField = new javax.swing.JTextField();
        lblnumeral = new javax.swing.JLabel();
        nombreAltaField = new javax.swing.JTextField();
        lblnombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        subcatAltaField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descAltaField = new javax.swing.JTextArea();
        marcaAltaField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        noSerieAltaField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        modeloAltaField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        colorAltaField = new javax.swing.JTextField();
        fechaComAltaField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        noFacAltaField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cantidadAltaField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        importeAltaField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        obsAltaField = new javax.swing.JTextArea();
        cantMinAltaField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        guardarAltaBtn = new javax.swing.JButton();
        panelAuto = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        placaAltaField = new javax.swing.JTextField();
        motorAltaField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        kilomAltaField = new javax.swing.JTextField();
        kilomMaxAltaField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Cancelar = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox<>();
        ID1 = new javax.swing.JLabel();
        ID2 = new javax.swing.JLabel();
        comboClas = new javax.swing.JComboBox<>();
        panelInventario = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        buscarField = new javax.swing.JTextField();
        panelModificar = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        idModField = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        numeralModField = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        nombreModField = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        subcatModField = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        descModField = new javax.swing.JTextArea();
        marcaModField = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        noSerieModField = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        modeloModField = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        colorModField = new javax.swing.JTextField();
        fechaComModField = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        noFacModField = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        cantidadModField = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        importeModField = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        obsModField = new javax.swing.JTextArea();
        cantMinModField = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        guardarModBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        placaModField = new javax.swing.JTextField();
        motorModField = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        kilomModField = new javax.swing.JTextField();
        kilomMaxModField = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        cancelarModBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1310, 820));
        getContentPane().setLayout(null);

        BarraLatera.setBackground(new java.awt.Color(255, 255, 255));
        BarraLatera.setLayout(null);

        modificarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        modificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBtnActionPerformed(evt);
            }
        });
        BarraLatera.add(modificarBtn);
        modificarBtn.setBounds(0, 350, 190, 70);

        darDeBajaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Baja.png"))); // NOI18N
        BarraLatera.add(darDeBajaBtn);
        darDeBajaBtn.setBounds(0, 420, 190, 70);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        logo.setPreferredSize(new java.awt.Dimension(150, 120));
        BarraLatera.add(logo);
        logo.setBounds(20, 70, 150, 120);

        atrasBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.png"))); // NOI18N
        atrasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBtnActionPerformed(evt);
            }
        });
        BarraLatera.add(atrasBtn);
        atrasBtn.setBounds(0, 0, 40, 30);

        darDeAltaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DarAlta.png"))); // NOI18N
        darDeAltaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darDeAltaBtnActionPerformed(evt);
            }
        });
        BarraLatera.add(darDeAltaBtn);
        darDeAltaBtn.setBounds(0, 280, 190, 70);

        inventarioBtn.setBackground(new java.awt.Color(255, 255, 255));
        inventarioBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/InventarioAct.png"))); // NOI18N
        inventarioBtn.setBorder(null);
        inventarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioBtnActionPerformed(evt);
            }
        });
        BarraLatera.add(inventarioBtn);
        inventarioBtn.setBounds(0, 210, 190, 70);

        getContentPane().add(BarraLatera);
        BarraLatera.setBounds(0, 0, 190, 830);

        areaAcción.setBackground(new java.awt.Color(255, 255, 255));
        areaAcción.setLayout(null);

        panelAlta.setBackground(new java.awt.Color(255, 255, 255));
        panelAlta.setOpaque(false);
        panelAlta.setLayout(null);

        idAltaField.setEditable(false);
        panelAlta.add(idAltaField);
        idAltaField.setBounds(150, 160, 170, 30);

        ID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ID.setText("Status");
        panelAlta.add(ID);
        ID.setBounds(710, 160, 60, 30);
        panelAlta.add(numeralAltaField);
        numeralAltaField.setBounds(150, 220, 130, 30);

        lblnumeral.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblnumeral.setText("Numeral:");
        panelAlta.add(lblnumeral);
        lblnumeral.setBounds(70, 220, 110, 30);
        panelAlta.add(nombreAltaField);
        nombreAltaField.setBounds(150, 270, 300, 30);

        lblnombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblnombre.setText("Nombre:");
        panelAlta.add(lblnombre);
        lblnombre.setBounds(70, 270, 80, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Sub Categoria:");
        panelAlta.add(jLabel3);
        jLabel3.setBounds(300, 220, 120, 30);
        panelAlta.add(subcatAltaField);
        subcatAltaField.setBounds(430, 220, 220, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Descripción:");
        panelAlta.add(jLabel5);
        jLabel5.setBounds(480, 270, 110, 30);

        descAltaField.setColumns(20);
        descAltaField.setRows(5);
        jScrollPane2.setViewportView(descAltaField);

        panelAlta.add(jScrollPane2);
        jScrollPane2.setBounds(600, 270, 350, 70);
        panelAlta.add(marcaAltaField);
        marcaAltaField.setBounds(150, 410, 170, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Marca:");
        panelAlta.add(jLabel12);
        jLabel12.setBounds(70, 410, 110, 30);
        panelAlta.add(noSerieAltaField);
        noSerieAltaField.setBounds(740, 410, 210, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("No. de Serie:");
        panelAlta.add(jLabel13);
        jLabel13.setBounds(610, 410, 130, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Modelo:");
        panelAlta.add(jLabel6);
        jLabel6.setBounds(340, 410, 90, 30);
        panelAlta.add(modeloAltaField);
        modeloAltaField.setBounds(450, 410, 130, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Color:");
        panelAlta.add(jLabel14);
        jLabel14.setBounds(70, 320, 110, 30);
        panelAlta.add(colorAltaField);
        colorAltaField.setBounds(140, 320, 300, 30);
        panelAlta.add(fechaComAltaField);
        fechaComAltaField.setBounds(190, 360, 120, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Fecha compra:");
        panelAlta.add(jLabel8);
        jLabel8.setBounds(70, 360, 120, 30);
        panelAlta.add(noFacAltaField);
        noFacAltaField.setBounds(440, 360, 130, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("No. Factura:");
        panelAlta.add(jLabel16);
        jLabel16.setBounds(340, 360, 120, 30);
        panelAlta.add(cantidadAltaField);
        cantidadAltaField.setBounds(150, 460, 170, 30);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Cantidad:");
        panelAlta.add(jLabel17);
        jLabel17.setBounds(70, 460, 120, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Importe:");
        panelAlta.add(jLabel9);
        jLabel9.setBounds(610, 360, 80, 30);
        panelAlta.add(importeAltaField);
        importeAltaField.setBounds(690, 360, 170, 30);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Observaciones:");
        panelAlta.add(jLabel18);
        jLabel18.setBounds(340, 460, 120, 30);

        obsAltaField.setColumns(20);
        obsAltaField.setRows(5);
        jScrollPane3.setViewportView(obsAltaField);

        panelAlta.add(jScrollPane3);
        jScrollPane3.setBounds(470, 460, 480, 90);
        panelAlta.add(cantMinAltaField);
        cantMinAltaField.setBounds(200, 510, 120, 30);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Cantidad (Min):");
        panelAlta.add(jLabel19);
        jLabel19.setBounds(70, 510, 120, 30);

        guardarAltaBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guardarAltaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        guardarAltaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarAltaBtnActionPerformed(evt);
            }
        });
        panelAlta.add(guardarAltaBtn);
        guardarAltaBtn.setBounds(660, 710, 125, 40);

        panelAuto.setBackground(new java.awt.Color(255, 255, 255));
        panelAuto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vehículo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        panelAuto.setOpaque(false);
        panelAuto.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Placa:");
        panelAuto.add(jLabel7);
        jLabel7.setBounds(40, 30, 130, 30);
        panelAuto.add(placaAltaField);
        placaAltaField.setBounds(130, 30, 270, 30);
        panelAuto.add(motorAltaField);
        motorAltaField.setBounds(130, 80, 270, 30);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Motor:");
        panelAuto.add(jLabel15);
        jLabel15.setBounds(40, 80, 120, 30);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Kilometraje (Max):");
        panelAuto.add(jLabel20);
        jLabel20.setBounds(460, 80, 150, 30);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Kilometraje:");
        panelAuto.add(jLabel21);
        jLabel21.setBounds(460, 30, 100, 30);
        panelAuto.add(kilomAltaField);
        kilomAltaField.setBounds(570, 30, 280, 30);
        panelAuto.add(kilomMaxAltaField);
        kilomMaxAltaField.setBounds(620, 80, 230, 30);

        panelAlta.add(panelAuto);
        panelAuto.setBounds(70, 570, 880, 120);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Rellena los campos siguientes para agregar un nuevo artículo al inventario.");
        panelAlta.add(jLabel1);
        jLabel1.setBounds(70, 120, 880, 20);

        Cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        panelAlta.add(Cancelar);
        Cancelar.setBounds(820, 710, 125, 40);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Formulario Registro de Artículo");
        panelAlta.add(jLabel24);
        jLabel24.setBounds(70, 40, 590, 90);

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Baja", "Comodato", "Donación" }));
        panelAlta.add(comboStatus);
        comboStatus.setBounds(790, 160, 160, 30);

        ID1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ID1.setText("ID:");
        panelAlta.add(ID1);
        ID1.setBounds(70, 160, 70, 30);

        ID2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ID2.setText("Clasificacion");
        panelAlta.add(ID2);
        ID2.setBounds(360, 160, 110, 30);

        comboClas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobiliario", "Comunicación", "Fotografia y Video", "A/C", "Comunicación 2", "Audiovisuales", "Diverso", "Transporte" }));
        comboClas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboClasActionPerformed(evt);
            }
        });
        panelAlta.add(comboClas);
        comboClas.setBounds(470, 160, 160, 30);

        areaAcción.add(panelAlta);
        panelAlta.setBounds(0, 0, 1110, 810);

        panelInventario.setBackground(new java.awt.Color(255, 255, 255));
        panelInventario.setOpaque(false);
        panelInventario.setLayout(null);

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaInventarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaInventario);

        panelInventario.add(jScrollPane1);
        jScrollPane1.setBounds(70, 180, 1000, 580);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Inventario Sistema");
        panelInventario.add(jLabel22);
        jLabel22.setBounds(70, 40, 480, 90);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        panelInventario.add(jButton1);
        jButton1.setBounds(380, 120, 125, 40);

        buscarField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelInventario.add(buscarField);
        buscarField.setBounds(70, 120, 270, 40);

        areaAcción.add(panelInventario);
        panelInventario.setBounds(0, 0, 1110, 840);

        panelModificar.setBackground(new java.awt.Color(255, 255, 255));
        panelModificar.setOpaque(false);
        panelModificar.setLayout(null);

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel43.setText("Modificar Información de Artículo");
        panelModificar.add(jLabel43);
        jLabel43.setBounds(70, 40, 590, 90);
        panelModificar.add(idModField);
        idModField.setBounds(150, 160, 170, 30);

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel44.setText("ID:");
        panelModificar.add(jLabel44);
        jLabel44.setBounds(70, 160, 70, 30);
        panelModificar.add(numeralModField);
        numeralModField.setBounds(450, 160, 130, 30);

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel45.setText("Numeral:");
        panelModificar.add(jLabel45);
        jLabel45.setBounds(340, 160, 110, 30);
        panelModificar.add(nombreModField);
        nombreModField.setBounds(150, 210, 300, 30);

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel46.setText("Nombre:");
        panelModificar.add(jLabel46);
        jLabel46.setBounds(70, 210, 80, 30);

        jLabel47.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel47.setText("Sub Categoria:");
        panelModificar.add(jLabel47);
        jLabel47.setBounds(600, 160, 120, 30);
        panelModificar.add(subcatModField);
        subcatModField.setBounds(730, 160, 220, 30);

        jLabel48.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel48.setText("Descripción:");
        panelModificar.add(jLabel48);
        jLabel48.setBounds(480, 210, 110, 30);

        descModField.setColumns(20);
        descModField.setRows(5);
        jScrollPane6.setViewportView(descModField);

        panelModificar.add(jScrollPane6);
        jScrollPane6.setBounds(600, 210, 350, 130);
        panelModificar.add(marcaModField);
        marcaModField.setBounds(150, 410, 170, 30);

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel49.setText("Marca:");
        panelModificar.add(jLabel49);
        jLabel49.setBounds(70, 410, 110, 30);
        panelModificar.add(noSerieModField);
        noSerieModField.setBounds(740, 410, 210, 30);

        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel50.setText("No. de Serie:");
        panelModificar.add(jLabel50);
        jLabel50.setBounds(610, 410, 130, 30);

        jLabel51.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel51.setText("Modelo:");
        panelModificar.add(jLabel51);
        jLabel51.setBounds(340, 410, 90, 30);
        panelModificar.add(modeloModField);
        modeloModField.setBounds(450, 410, 130, 30);

        jLabel52.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel52.setText("Color:");
        panelModificar.add(jLabel52);
        jLabel52.setBounds(70, 260, 110, 30);
        panelModificar.add(colorModField);
        colorModField.setBounds(150, 260, 300, 30);
        panelModificar.add(fechaComModField);
        fechaComModField.setBounds(200, 310, 120, 30);

        jLabel53.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel53.setText("Fecha compra:");
        panelModificar.add(jLabel53);
        jLabel53.setBounds(70, 310, 120, 30);
        panelModificar.add(noFacModField);
        noFacModField.setBounds(450, 310, 130, 30);

        jLabel54.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel54.setText("No. Factura:");
        panelModificar.add(jLabel54);
        jLabel54.setBounds(340, 310, 120, 30);
        panelModificar.add(cantidadModField);
        cantidadModField.setBounds(150, 460, 170, 30);

        jLabel55.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel55.setText("Cantidad:");
        panelModificar.add(jLabel55);
        jLabel55.setBounds(70, 460, 120, 30);

        jLabel56.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel56.setText("Importe:");
        panelModificar.add(jLabel56);
        jLabel56.setBounds(70, 360, 120, 30);
        panelModificar.add(importeModField);
        importeModField.setBounds(150, 360, 170, 30);

        jLabel57.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel57.setText("Observaciones:");
        panelModificar.add(jLabel57);
        jLabel57.setBounds(340, 460, 120, 30);

        obsModField.setColumns(20);
        obsModField.setRows(5);
        jScrollPane7.setViewportView(obsModField);

        panelModificar.add(jScrollPane7);
        jScrollPane7.setBounds(470, 460, 480, 90);
        panelModificar.add(cantMinModField);
        cantMinModField.setBounds(200, 510, 120, 30);

        jLabel58.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel58.setText("Cantidad (Min):");
        panelModificar.add(jLabel58);
        jLabel58.setBounds(70, 510, 120, 30);

        guardarModBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guardarModBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        panelModificar.add(guardarModBtn);
        guardarModBtn.setBounds(660, 710, 125, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vehículo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jLabel59.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel59.setText("Placa:");
        jPanel2.add(jLabel59);
        jLabel59.setBounds(40, 30, 130, 30);
        jPanel2.add(placaModField);
        placaModField.setBounds(130, 30, 270, 30);
        jPanel2.add(motorModField);
        motorModField.setBounds(130, 80, 270, 30);

        jLabel60.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel60.setText("Motor:");
        jPanel2.add(jLabel60);
        jLabel60.setBounds(40, 80, 120, 30);

        jLabel61.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel61.setText("Kilometraje (Max):");
        jPanel2.add(jLabel61);
        jLabel61.setBounds(460, 80, 150, 30);

        jLabel62.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel62.setText("Kilometraje:");
        jPanel2.add(jLabel62);
        jLabel62.setBounds(460, 30, 100, 30);
        jPanel2.add(kilomModField);
        kilomModField.setBounds(570, 30, 280, 30);
        jPanel2.add(kilomMaxModField);
        kilomMaxModField.setBounds(620, 80, 230, 30);

        panelModificar.add(jPanel2);
        jPanel2.setBounds(70, 570, 880, 120);

        jLabel63.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel63.setText("Modifica los campos siguientes para editar la información de algun artículo seleccionado en el inventario.");
        panelModificar.add(jLabel63);
        jLabel63.setBounds(70, 120, 880, 20);

        cancelarModBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelarModBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        cancelarModBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarModBtnActionPerformed(evt);
            }
        });
        panelModificar.add(cancelarModBtn);
        cancelarModBtn.setBounds(820, 710, 125, 40);

        areaAcción.add(panelModificar);
        panelModificar.setBounds(0, 0, 1110, 810);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Instituto Estatal Electoral de Nayarit");
        areaAcción.add(jLabel4);
        jLabel4.setBounds(70, 0, 630, 40);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BackgroundGeneral.png"))); // NOI18N
        areaAcción.add(jLabel23);
        jLabel23.setBounds(0, 0, 1110, 840);

        getContentPane().add(areaAcción);
        areaAcción.setBounds(190, 0, 1110, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void primeraCarga(){
        String[] titulos={"ID","clave","Nombre","Marca","Serie","Color","Placas","Stock"};

        String[] registros= new String[8];
        modelo = new DefaultTableModel(null,titulos);
        try {
            //Mostrar registros en la tabla
            con = new conexion();
            ResultSet consulta= con.primerCarga();
            while(consulta.next()){
                registros[0] = consulta.getString("idproductos");
                registros[1] = consulta.getString("clave");
                registros[2] = consulta.getString("nom_pro");
                registros[3] = consulta.getString("mar_pro");
                registros[4] = consulta.getString("ser_pro");
                registros[5] = consulta.getString("col_pro");
                registros[6] = consulta.getString("placas");
                registros[7] = consulta.getString("stock_pro");
                modelo.addRow(registros);               
            }
            //Mostrar titulos de la tabla
            tablaInventario.setModel(modelo);
            
        } catch (SQLException ex) {    
            JOptionPane.showMessageDialog(null,ex);
        }
    }
    
    private void atrasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBtnActionPerformed
        this.setVisible(false);
        new ventanaInicio().setVisible(true);
    }//GEN-LAST:event_atrasBtnActionPerformed

    private void inventarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioBtnActionPerformed
        panelAlta.setVisible(false);
        panelInventario.setVisible(true);
        panelModificar.setVisible(false);
        primeraCarga();
        
    }//GEN-LAST:event_inventarioBtnActionPerformed

    private void darDeAltaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darDeAltaBtnActionPerformed
        panelAlta.setVisible(true);
        panelInventario.setVisible(false);
        panelModificar.setVisible(false);
        panelAuto.setVisible(false);
        
    }//GEN-LAST:event_darDeAltaBtnActionPerformed

    private void modificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBtnActionPerformed
        panelAlta.setVisible(false);
        panelInventario.setVisible(false);
        panelModificar.setVisible(true);
    }//GEN-LAST:event_modificarBtnActionPerformed

    private void cancelarModBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarModBtnActionPerformed
    cantMinModField.setText("");
    cantidadModField.setText("");
    colorModField.setText("");
    descModField.setText("");
    fechaComModField.setText("");
    idModField.setText("");
    importeModField.setText("");
    buscarField.setText("");
    kilomMaxModField.setText("");
    kilomModField.setText("");
    marcaModField.setText("");
    modeloModField.setText("");
    motorModField.setText("");
    noFacModField.setText("");
    noSerieModField.setText("");
    nombreModField.setText("");
    numeralModField.setText("");
    obsModField.setText("");
    placaModField.setText("");
    subcatModField.setText("");
    }//GEN-LAST:event_cancelarModBtnActionPerformed

    private boolean validacion(String Numeral, String Sub_cat, String Nombre, String Color, 
            String Descripcion, String Fecha_compra, String No_Factura, String importe, String marca, 
            String modelo, String no_serie, String cantidad, String observaciones, String cantidad_min, 
            String placa, String km, String motor, String km_max) {
        if(Numeral.equals("") || Sub_cat.equals("") || Nombre.equals("") || Color.equals("")
           || Descripcion.equals("") || Fecha_compra.equals("") || No_Factura.equals("") || importe.equals("") || marca.equals("") ||
           no_serie.equals("") || cantidad.equals("") || observaciones.equals("") || cantidad_min.equals("") || placa.equals("") || 
           km.equals("") || motor.equals("") || km_max.equals("")){
            showMessageDialog(this,"LLene todos los campos necesarios","AVISO!",INFORMATION_MESSAGE);
            validacion = false;
            return validacion;
        }else {
            return validacion;
        }
    }
    private void guardarAltaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarAltaBtnActionPerformed
    String Numeral,Sub_cat,Nombre,Descripcion,marca,modelo,no_serie,Color,placa,motor,Fecha_compra,No_Factura,
           observaciones;
    int ID,status,clasificacion,cantidad,cantidad_min,km,km_max;
    
    double importe;
    
    status = comboStatus.getSelectedIndex()+1;
    clasificacion = comboClas.getSelectedIndex()+1;
    ID = Integer.valueOf(idAltaField.getText());
    Numeral = numeralAltaField.getText();
    Sub_cat = subcatAltaField.getText();
    Nombre = nombreAltaField.getText();
    Color = colorAltaField.getText();
    Descripcion = descAltaField.getText();
    Fecha_compra = fechaComAltaField.getText();
    No_Factura = noFacAltaField.getText();
    importe = Double.valueOf(importeAltaField.getText());
    marca = marcaAltaField.getText();
    modelo = modeloAltaField.getText();
    no_serie = noSerieAltaField.getText();
    cantidad = Integer.valueOf(cantidadAltaField.getText());
    observaciones = obsAltaField.getText();
    cantidad_min = Integer.valueOf(cantMinAltaField.getText());
    placa = placaAltaField.getText();
    km = Integer.valueOf(kilomAltaField.getText());
    motor = motorAltaField.getText();
    km_max = Integer.valueOf(kilomMaxAltaField.getText());
    
    //validacion(Numeral, Sub_cat, Nombre, Color, Descripcion, Fecha_compra, No_Factura, importe, marca, modelo,
      //         no_serie, cantidad, observaciones, cantidad_min, placa, km, motor, km_max);
    
    //if(validacion == true){
         try {
            System.out.println("Previo a conexion..."); 
            con = new conexion(); 
            if(accion.equals("Insertar")){
                sql= "INSERT INTO productos( ,Apellido,Departamento,Direccion,Secretaria,Domicilio,Telefono_oficina,Telefono_celular,Correo,Observaciones)"+" VALUES(?,?,?,?,?,?,?,?,?,?)";
                mensaje="Los datos se han insertado";
            }
            
            if((accion.equals("Modificar"))){
                System.out.println("Estoy actualizando...");
                sql= "UPDATE Contacto SET Nombre = ?, Apellido = ?,Departamento = ?,Direccion = ?,Secretaria = ?, Domicilio = ?,Telefono_oficina = ?,Telefono_celular = ?,Correo = ?,Observaciones = ? WHERE Nombre = "+"'"+id_actualizar+"'";
                mensaje="Los datos se han actualizado";
            }PreparedStatement pst=con.conectar.prepareStatement(sql);
            pst.setString(1, ID);
            pst.setString(2, ape);
            pst.setString(3, dep);
            pst.setString(4, dir);
            pst.setString(5, sec);
            pst.setString(6, dom);
            pst.setString(7, telof);
            pst.setString(8, telcel);
            pst.setString(9, corr);
            pst.setString(10, observ);
           
            int n=pst.executeUpdate();
            System.out.println("Valor n= "+n);
            if(n>0){
                JOptionPane.showMessageDialog(null, mensaje);
                primeraCarga();
            }
        } catch (SQLException ex) {
           System.out.println("Entró a catch...");
           JOptionPane.showMessageDialog(null, ex);
        }
   // }
  //  borrarCampos();
    }//GEN-LAST:event_guardarAltaBtnActionPerformed

    private void comboClasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboClasActionPerformed
        if(comboClas.getSelectedIndex()!=7){
            panelAuto.setVisible(false);
        }else if(comboClas.getSelectedIndex()==7) 
            panelAuto.setVisible(true);
    }//GEN-LAST:event_comboClasActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
    borrarCampos();
    }//GEN-LAST:event_CancelarActionPerformed

    private void tablaInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaInventarioMouseClicked
        int filas;
        String Id;
        accion="Modificar";
        filas= tablaInventario.getSelectedRow();
        Id=(String)modelo.getValueAt(filas,0);
        System.out.println("Valor ID= "+Id);
        id_actualizar = Id;
        cargarDatos(Id);
        modificarBtn.setEnabled(true);
    }//GEN-LAST:event_tablaInventarioMouseClicked

    private void cargarDatos(String Id){
        try {
            con = new conexion();
            ResultSet consulta = con.Consultar2("productos", "idproductos", Id);
            //Recorre registros para mostrarlos
            while(consulta.next()){
                idAltaField.setText(consulta.getString("idproductos"));
                numeralAltaField.setText(consulta.getString("con_pro"));
                subcatAltaField.setText(consulta.getString("subcat_pro"));
                nombreAltaField.setText(consulta.getString("nom_pro"));
                descAltaField.setText(consulta.getString("des_pro"));
                marcaAltaField.setText(consulta.getString("mar_pro"));
                modeloAltaField.setText(consulta.getString("mod_pro"));
                noSerieAltaField.setText(consulta.getString("ser_pro"));
                colorAltaField.setText(consulta.getString("col_pro"));
                placaAltaField.setText(consulta.getString("pla_pro"));
                motorAltaField.setText(consulta.getString("nomot_pro"));
                fechaComAltaField.setText(consulta.getString("fechcompra_pro"));
                noFacAltaField.setText(consulta.getString("nofact_pro"));
                importeAltaField.setText(consulta.getString("imp_pro"));
                obsAltaField.setText(consulta.getString("obs_pro"));
                cantidadAltaField.setText(consulta.getString("stock_pro"));
                cantMinAltaField.setText(consulta.getString("stockmin_pro"));
                kilomAltaField.setText(consulta.getString("km_pro"));
                kilomMaxAltaField.setText(consulta.getString("km_ser_pro"));
                comboStatus.setSelectedIndex(Integer.valueOf(consulta.getString("status_id_status")));
                comboClas.setSelectedIndex(Integer.valueOf(consulta.getString("clasificacion_id_clas")));
            }
            
        } catch (SQLException ex) {}
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraLatera;
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel ID1;
    private javax.swing.JLabel ID2;
    private javax.swing.JPanel areaAcción;
    private javax.swing.JButton atrasBtn;
    private javax.swing.JTextField buscarField;
    private javax.swing.JButton cancelarModBtn;
    private javax.swing.JTextField cantMinAltaField;
    private javax.swing.JTextField cantMinModField;
    private javax.swing.JTextField cantidadAltaField;
    private javax.swing.JTextField cantidadModField;
    private javax.swing.JTextField colorAltaField;
    private javax.swing.JTextField colorModField;
    private javax.swing.JComboBox<String> comboClas;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JButton darDeAltaBtn;
    private javax.swing.JButton darDeBajaBtn;
    private javax.swing.JTextArea descAltaField;
    private javax.swing.JTextArea descModField;
    private javax.swing.JTextField fechaComAltaField;
    private javax.swing.JTextField fechaComModField;
    private javax.swing.JButton guardarAltaBtn;
    private javax.swing.JButton guardarModBtn;
    private javax.swing.JTextField idAltaField;
    private javax.swing.JTextField idModField;
    private javax.swing.JTextField importeAltaField;
    private javax.swing.JTextField importeModField;
    private javax.swing.JButton inventarioBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField kilomAltaField;
    private javax.swing.JTextField kilomMaxAltaField;
    private javax.swing.JTextField kilomMaxModField;
    private javax.swing.JTextField kilomModField;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblnumeral;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField marcaAltaField;
    private javax.swing.JTextField marcaModField;
    private javax.swing.JTextField modeloAltaField;
    private javax.swing.JTextField modeloModField;
    private javax.swing.JButton modificarBtn;
    private javax.swing.JTextField motorAltaField;
    private javax.swing.JTextField motorModField;
    private javax.swing.JTextField noFacAltaField;
    private javax.swing.JTextField noFacModField;
    private javax.swing.JTextField noSerieAltaField;
    private javax.swing.JTextField noSerieModField;
    private javax.swing.JTextField nombreAltaField;
    private javax.swing.JTextField nombreModField;
    private javax.swing.JTextField numeralAltaField;
    private javax.swing.JTextField numeralModField;
    private javax.swing.JTextArea obsAltaField;
    private javax.swing.JTextArea obsModField;
    private javax.swing.JPanel panelAlta;
    private javax.swing.JPanel panelAuto;
    private javax.swing.JPanel panelInventario;
    private javax.swing.JPanel panelModificar;
    private javax.swing.JTextField placaAltaField;
    private javax.swing.JTextField placaModField;
    private javax.swing.JTextField subcatAltaField;
    private javax.swing.JTextField subcatModField;
    private javax.swing.JTable tablaInventario;
    // End of variables declaration//GEN-END:variables

    private void borrarCampos() {
        idAltaField.setText("");
    numeralAltaField.setText("");
    subcatAltaField.setText("");
    nombreAltaField.setText("");
    colorAltaField.setText("");
    descAltaField.setText("");
    fechaComAltaField.setText("");
    noFacAltaField.setText("");
    importeAltaField.setText("");
    marcaAltaField.setText("");
    modeloAltaField.setText("");
    noSerieAltaField.setText("");
    cantidadAltaField.setText("");
    obsAltaField.setText("");
    cantMinAltaField.setText("");
    placaAltaField.setText("");
    kilomAltaField.setText("");
    motorAltaField.setText("");
    kilomMaxAltaField.setText("");
    }
}
