/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author angel
 */
public class ventanaSolicitar extends javax.swing.JFrame {

    /**
     * Creates new form ventanaSolicitar
     */
    public ventanaSolicitar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraLatera = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        atrasBtn = new javax.swing.JButton();
        inventarioBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panelUsuarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAgregados = new javax.swing.JTable();
        barraBusqueda = new javax.swing.JTextField();
        removerBtn = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        enviarBtn = new javax.swing.JButton();
        agregarBtn = new javax.swing.JButton();
        buscarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1310, 690));
        setPreferredSize(new java.awt.Dimension(1310, 690));
        getContentPane().setLayout(null);

        BarraLatera.setBackground(new java.awt.Color(255, 255, 255));
        BarraLatera.setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        logo.setPreferredSize(new java.awt.Dimension(150, 120));
        BarraLatera.add(logo);
        logo.setBounds(20, 70, 150, 120);

        atrasBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.png"))); // NOI18N
        atrasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBtnActionPerformed(evt);
            }
        });
        BarraLatera.add(atrasBtn);
        atrasBtn.setBounds(0, 0, 40, 30);

        inventarioBtn.setBackground(new java.awt.Color(255, 255, 255));
        inventarioBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SolicitudesAct.png"))); // NOI18N
        inventarioBtn.setBorder(null);
        inventarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioBtnActionPerformed(evt);
            }
        });
        BarraLatera.add(inventarioBtn);
        inventarioBtn.setBounds(0, 210, 190, 70);

        getContentPane().add(BarraLatera);
        BarraLatera.setBounds(0, 0, 190, 640);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        panelUsuarios.setOpaque(false);
        panelUsuarios.setLayout(null);

        tablaAgregados.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tablaAgregados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaAgregados);

        panelUsuarios.add(jScrollPane1);
        jScrollPane1.setBounds(70, 410, 1000, 180);

        barraBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelUsuarios.add(barraBusqueda);
        barraBusqueda.setBounds(70, 120, 270, 40);

        removerBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Remover.png"))); // NOI18N
        panelUsuarios.add(removerBtn);
        removerBtn.setBounds(600, 360, 45, 40);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Usuarios del Sistema");
        panelUsuarios.add(jLabel22);
        jLabel22.setBounds(70, 40, 480, 90);

        tablaInventario.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaInventario);

        panelUsuarios.add(jScrollPane2);
        jScrollPane2.setBounds(70, 180, 1000, 170);

        enviarBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        enviarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Enviar.png"))); // NOI18N
        panelUsuarios.add(enviarBtn);
        enviarBtn.setBounds(790, 120, 125, 40);

        agregarBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        agregarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        panelUsuarios.add(agregarBtn);
        agregarBtn.setBounds(520, 360, 45, 40);

        buscarBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        panelUsuarios.add(buscarBtn);
        buscarBtn.setBounds(380, 120, 125, 40);

        cancelarBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        panelUsuarios.add(cancelarBtn);
        cancelarBtn.setBounds(940, 120, 125, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BackgroundGeneral.png"))); // NOI18N
        panelUsuarios.add(jLabel1);
        jLabel1.setBounds(0, 0, 1110, 640);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo", "Prestamo", "Remplazo", "Como Dato", " " }));
        panelUsuarios.add(jComboBox1);
        jComboBox1.setBounds(530, 120, 190, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Instituto Estatal Electoral de Nayarit");
        panelUsuarios.add(jLabel4);
        jLabel4.setBounds(70, 0, 630, 40);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(190, 0, 1110, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBtnActionPerformed
        this.setVisible(false);
        new ventanaInicio().setVisible(true);
    }//GEN-LAST:event_atrasBtnActionPerformed

    private void inventarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioBtnActionPerformed
      
    }//GEN-LAST:event_inventarioBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaSolicitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaSolicitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaSolicitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaSolicitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaSolicitar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraLatera;
    private javax.swing.JButton agregarBtn;
    private javax.swing.JButton atrasBtn;
    private javax.swing.JTextField barraBusqueda;
    private javax.swing.JButton buscarBtn;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JButton enviarBtn;
    private javax.swing.JButton inventarioBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelUsuarios;
    private javax.swing.JButton removerBtn;
    private javax.swing.JTable tablaAgregados;
    private javax.swing.JTable tablaInventario;
    // End of variables declaration//GEN-END:variables
}
