
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author angel
 */
public class ventanaInventario extends javax.swing.JFrame {
    boolean validacion = true;
    conexion con;
    DefaultTableModel modelo;
    private String accion, id_actualizar,sql,mensaje;
    String campoconsulta;
    /**
     * Creates new form ventanaInventario
     */
    public ventanaInventario() {
        initComponents();
        this.setTitle("Inventario");
        
        panelAlta.setVisible(false);
        
        this.setLocationRelativeTo(null);
        
        primeraCarga();
        
        modificarBtn.setEnabled(false);
        
        darDeBajaBtn.setEnabled(false);
        
        accion = "Insertar";
        
        inventarioBtn.setEnabled(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraLatera = new javax.swing.JPanel();
        modificarBtn = new javax.swing.JButton();
        darDeBajaBtn = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        atrasBtn = new javax.swing.JButton();
        darDeAltaBtn = new javax.swing.JButton();
        inventarioBtn = new javax.swing.JButton();
        areaAcción = new javax.swing.JPanel();
        panelAlta = new javax.swing.JPanel();
        idAltaField = new javax.swing.JTextField();
        ID = new javax.swing.JLabel();
        numeralAltaField = new javax.swing.JTextField();
        lblnumeral = new javax.swing.JLabel();
        nombreAltaField = new javax.swing.JTextField();
        lblnombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        subcatAltaField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descAltaField = new javax.swing.JTextArea();
        marcaAltaField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        noSerieAltaField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        modeloAltaField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        colorAltaField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        noFacAltaField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cantidadAltaField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        importeAltaField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        obsAltaField = new javax.swing.JTextArea();
        cantMinAltaField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        guardarAltaBtn = new javax.swing.JButton();
        panelAuto = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        placaAltaField = new javax.swing.JTextField();
        motorAltaField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        kilomAltaField = new javax.swing.JTextField();
        kilomMaxAltaField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Cancelar = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox<>();
        ID1 = new javax.swing.JLabel();
        ID2 = new javax.swing.JLabel();
        comboClas = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        panelInventario = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        buscarField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1310, 820));
        getContentPane().setLayout(null);

        BarraLatera.setBackground(new java.awt.Color(255, 255, 255));
        BarraLatera.setLayout(null);

        modificarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        modificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBtnActionPerformed(evt);
            }
        });
        BarraLatera.add(modificarBtn);
        modificarBtn.setBounds(0, 350, 190, 70);

        darDeBajaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Baja.png"))); // NOI18N
        darDeBajaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darDeBajaBtnActionPerformed(evt);
            }
        });
        BarraLatera.add(darDeBajaBtn);
        darDeBajaBtn.setBounds(0, 420, 190, 70);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        logo.setPreferredSize(new java.awt.Dimension(150, 120));
        BarraLatera.add(logo);
        logo.setBounds(20, 70, 150, 120);

        atrasBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.png"))); // NOI18N
        atrasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBtnActionPerformed(evt);
            }
        });
        BarraLatera.add(atrasBtn);
        atrasBtn.setBounds(0, 0, 40, 30);

        darDeAltaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DarAlta.png"))); // NOI18N
        darDeAltaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darDeAltaBtnActionPerformed(evt);
            }
        });
        BarraLatera.add(darDeAltaBtn);
        darDeAltaBtn.setBounds(0, 280, 190, 70);

        inventarioBtn.setBackground(new java.awt.Color(255, 255, 255));
        inventarioBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/InventarioAct.png"))); // NOI18N
        inventarioBtn.setBorder(null);
        inventarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioBtnActionPerformed(evt);
            }
        });
        BarraLatera.add(inventarioBtn);
        inventarioBtn.setBounds(0, 210, 190, 70);

        getContentPane().add(BarraLatera);
        BarraLatera.setBounds(0, 0, 190, 830);

        areaAcción.setBackground(new java.awt.Color(255, 255, 255));
        areaAcción.setLayout(null);

        panelAlta.setBackground(new java.awt.Color(255, 255, 255));
        panelAlta.setOpaque(false);
        panelAlta.setLayout(null);

        idAltaField.setEditable(false);
        panelAlta.add(idAltaField);
        idAltaField.setBounds(150, 160, 170, 30);

        ID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ID.setText("Status");
        panelAlta.add(ID);
        ID.setBounds(710, 160, 60, 30);

        numeralAltaField.setEditable(false);
        panelAlta.add(numeralAltaField);
        numeralAltaField.setBounds(150, 220, 130, 30);

        lblnumeral.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblnumeral.setText("Numeral:");
        panelAlta.add(lblnumeral);
        lblnumeral.setBounds(70, 220, 110, 30);

        nombreAltaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreAltaFieldKeyTyped(evt);
            }
        });
        panelAlta.add(nombreAltaField);
        nombreAltaField.setBounds(150, 270, 300, 30);

        lblnombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblnombre.setText("Nombre:");
        panelAlta.add(lblnombre);
        lblnombre.setBounds(70, 270, 80, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Sub Categoria:");
        panelAlta.add(jLabel3);
        jLabel3.setBounds(340, 220, 120, 30);

        subcatAltaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                subcatAltaFieldKeyPressed(evt);
            }
        });
        panelAlta.add(subcatAltaField);
        subcatAltaField.setBounds(470, 220, 220, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Descripción:");
        panelAlta.add(jLabel5);
        jLabel5.setBounds(480, 270, 110, 30);

        descAltaField.setColumns(20);
        descAltaField.setRows(5);
        jScrollPane2.setViewportView(descAltaField);

        panelAlta.add(jScrollPane2);
        jScrollPane2.setBounds(600, 270, 350, 70);

        marcaAltaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                marcaAltaFieldKeyTyped(evt);
            }
        });
        panelAlta.add(marcaAltaField);
        marcaAltaField.setBounds(190, 410, 170, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Marca:");
        panelAlta.add(jLabel12);
        jLabel12.setBounds(130, 410, 110, 30);

        noSerieAltaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noSerieAltaFieldKeyTyped(evt);
            }
        });
        panelAlta.add(noSerieAltaField);
        noSerieAltaField.setBounds(720, 410, 230, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("No. de Serie:");
        panelAlta.add(jLabel13);
        jLabel13.setBounds(610, 410, 130, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Modelo:");
        panelAlta.add(jLabel6);
        jLabel6.setBounds(390, 410, 90, 30);
        panelAlta.add(modeloAltaField);
        modeloAltaField.setBounds(470, 410, 130, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Color:");
        panelAlta.add(jLabel14);
        jLabel14.setBounds(90, 320, 110, 30);

        colorAltaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                colorAltaFieldKeyTyped(evt);
            }
        });
        panelAlta.add(colorAltaField);
        colorAltaField.setBounds(150, 320, 300, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Fecha compra:");
        panelAlta.add(jLabel8);
        jLabel8.setBounds(70, 360, 120, 30);

        noFacAltaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noFacAltaFieldKeyTyped(evt);
            }
        });
        panelAlta.add(noFacAltaField);
        noFacAltaField.setBounds(470, 360, 130, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("No. Factura:");
        panelAlta.add(jLabel16);
        jLabel16.setBounds(370, 360, 120, 30);

        cantidadAltaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadAltaFieldKeyTyped(evt);
            }
        });
        panelAlta.add(cantidadAltaField);
        cantidadAltaField.setBounds(200, 460, 120, 30);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Cantidad:");
        panelAlta.add(jLabel17);
        jLabel17.setBounds(110, 460, 120, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Importe:");
        panelAlta.add(jLabel9);
        jLabel9.setBounds(640, 360, 80, 30);

        importeAltaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                importeAltaFieldKeyTyped(evt);
            }
        });
        panelAlta.add(importeAltaField);
        importeAltaField.setBounds(720, 360, 230, 30);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Observaciones:");
        panelAlta.add(jLabel18);
        jLabel18.setBounds(340, 460, 120, 30);

        obsAltaField.setColumns(20);
        obsAltaField.setRows(5);
        jScrollPane3.setViewportView(obsAltaField);

        panelAlta.add(jScrollPane3);
        jScrollPane3.setBounds(470, 460, 480, 90);

        cantMinAltaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantMinAltaFieldKeyTyped(evt);
            }
        });
        panelAlta.add(cantMinAltaField);
        cantMinAltaField.setBounds(200, 510, 120, 30);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Cantidad (Min):");
        panelAlta.add(jLabel19);
        jLabel19.setBounds(70, 510, 120, 30);

        guardarAltaBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guardarAltaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        guardarAltaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarAltaBtnActionPerformed(evt);
            }
        });
        panelAlta.add(guardarAltaBtn);
        guardarAltaBtn.setBounds(660, 710, 125, 40);

        panelAuto.setBackground(new java.awt.Color(255, 255, 255));
        panelAuto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vehículo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        panelAuto.setOpaque(false);
        panelAuto.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Placa:");
        panelAuto.add(jLabel7);
        jLabel7.setBounds(40, 30, 130, 30);
        panelAuto.add(placaAltaField);
        placaAltaField.setBounds(130, 30, 270, 30);

        motorAltaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                motorAltaFieldKeyTyped(evt);
            }
        });
        panelAuto.add(motorAltaField);
        motorAltaField.setBounds(130, 80, 270, 30);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Motor:");
        panelAuto.add(jLabel15);
        jLabel15.setBounds(40, 80, 120, 30);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Kilometraje (Max):");
        panelAuto.add(jLabel20);
        jLabel20.setBounds(460, 80, 150, 30);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Kilometraje:");
        panelAuto.add(jLabel21);
        jLabel21.setBounds(460, 30, 100, 30);

        kilomAltaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kilomAltaFieldKeyTyped(evt);
            }
        });
        panelAuto.add(kilomAltaField);
        kilomAltaField.setBounds(570, 30, 280, 30);

        kilomMaxAltaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kilomMaxAltaFieldKeyTyped(evt);
            }
        });
        panelAuto.add(kilomMaxAltaField);
        kilomMaxAltaField.setBounds(620, 80, 230, 30);

        panelAlta.add(panelAuto);
        panelAuto.setBounds(70, 570, 880, 120);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Rellena los campos siguientes para agregar un nuevo artículo al inventario.");
        panelAlta.add(jLabel1);
        jLabel1.setBounds(70, 120, 880, 20);

        Cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        panelAlta.add(Cancelar);
        Cancelar.setBounds(820, 710, 125, 40);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Formulario Registro de Artículo");
        panelAlta.add(jLabel24);
        jLabel24.setBounds(70, 40, 590, 90);

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Baja", "Comodato", "Donación" }));
        panelAlta.add(comboStatus);
        comboStatus.setBounds(790, 160, 160, 30);

        ID1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ID1.setText("ID:");
        panelAlta.add(ID1);
        ID1.setBounds(70, 160, 70, 30);

        ID2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ID2.setText("Clasificacion");
        panelAlta.add(ID2);
        ID2.setBounds(360, 160, 110, 30);

        comboClas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobiliario", "Comunicación", "Fotografia y Video", "A/C", "Comunicación 2", "Audiovisuales", "Diverso", "Transporte" }));
        comboClas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboClasActionPerformed(evt);
            }
        });
        panelAlta.add(comboClas);
        comboClas.setBounds(470, 160, 160, 30);
        panelAlta.add(jDateChooser1);
        jDateChooser1.setBounds(190, 360, 170, 30);

        areaAcción.add(panelAlta);
        panelAlta.setBounds(0, 0, 1110, 810);

        panelInventario.setBackground(new java.awt.Color(255, 255, 255));
        panelInventario.setOpaque(false);
        panelInventario.setLayout(null);

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaInventarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaInventario);

        panelInventario.add(jScrollPane1);
        jScrollPane1.setBounds(70, 180, 1000, 580);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Inventario Sistema");
        panelInventario.add(jLabel22);
        jLabel22.setBounds(70, 40, 480, 90);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        panelInventario.add(jButton1);
        jButton1.setBounds(380, 120, 125, 40);

        buscarField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscarField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarFieldKeyReleased(evt);
            }
        });
        panelInventario.add(buscarField);
        buscarField.setBounds(70, 120, 270, 40);

        areaAcción.add(panelInventario);
        panelInventario.setBounds(0, 0, 1110, 840);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Instituto Estatal Electoral de Nayarit");
        areaAcción.add(jLabel4);
        jLabel4.setBounds(70, 0, 630, 40);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BackgroundGeneral.png"))); // NOI18N
        areaAcción.add(jLabel23);
        jLabel23.setBounds(0, 0, 1110, 840);

        getContentPane().add(areaAcción);
        areaAcción.setBounds(190, 0, 1110, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void primeraCarga(){
        String[] titulos={"ID","clave","Nombre","Marca","Serie","Color","Placas","Stock"};

        String[] registros= new String[8];
        modelo = new DefaultTableModel(null,titulos);
        try {
            //Mostrar registros en la tabla
            con = new conexion();
            ResultSet consulta= con.primerCarga();
            while(consulta.next()){
                registros[0] = consulta.getString("idproductos");
                registros[1] = consulta.getString("clave");
                registros[2] = consulta.getString("nom_pro");
                registros[3] = consulta.getString("mar_pro");
                registros[4] = consulta.getString("ser_pro");
                registros[5] = consulta.getString("col_pro");
                registros[6] = consulta.getString("placas");
                registros[7] = consulta.getString("stock_pro");
                modelo.addRow(registros);               
            }
            //Mostrar titulos de la tabla
            tablaInventario.setModel(modelo);
            
        } catch (SQLException ex) {    
            JOptionPane.showMessageDialog(null,ex);
        }
    }
    
    private void atrasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBtnActionPerformed
        this.setVisible(false);
        new ventanaInicio().setVisible(true);
    }//GEN-LAST:event_atrasBtnActionPerformed

    private void inventarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioBtnActionPerformed
        inventarioBtn.setEnabled(false);
        darDeAltaBtn.setEnabled(true);
        modificarBtn.setEnabled(false);
        panelAlta.setVisible(false);
        panelInventario.setVisible(true);
        comboClas.setSelectedIndex(0);
        comboStatus.setSelectedIndex(0);
        primeraCarga();
        
    }//GEN-LAST:event_inventarioBtnActionPerformed

    private void darDeAltaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darDeAltaBtnActionPerformed
        inventarioBtn.setEnabled(true);
        modificarBtn.setEnabled(false);
        darDeAltaBtn.setEnabled(false);
        accion = "Insertar";
        borrarCampos();
        panelAlta.setVisible(true);
        panelInventario.setVisible(false);
        panelAuto.setVisible(false);
        comboClas.setSelectedIndex(0);
        comboStatus.setSelectedIndex(0);
        
        cargarNuevoProducto();
        
        
    }//GEN-LAST:event_darDeAltaBtnActionPerformed

    private void modificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBtnActionPerformed
        darDeAltaBtn.setEnabled(true);
        modificarBtn.setEnabled(false);
        inventarioBtn.setEnabled(true);
        accion = "Modificar";
        panelAlta.setVisible(true);
        panelInventario.setVisible(false);
    }//GEN-LAST:event_modificarBtnActionPerformed

    private boolean validacion(String Numeral, String Sub_cat, String Nombre, String Color, 
            String Descripcion, String Fecha_compra, String No_Factura, String importe, String marca, 
            String modelo, String no_serie, String cantidad, String observaciones, String cantidad_min, 
            String placa, String km, String motor, String km_max) {
        if(Numeral.equals("") || Sub_cat.equals("") || Nombre.equals("") || Color.equals("")
           || Descripcion.equals("") || Fecha_compra.equals("") || No_Factura.equals("") || importe.equals("") || marca.equals("") ||
           no_serie.equals("") || cantidad.equals("") || observaciones.equals("") || cantidad_min.equals("") || placa.equals("") || 
           km.equals("") || motor.equals("") || km_max.equals("")){
            showMessageDialog(this,"LLene todos los campos necesarios","AVISO!",INFORMATION_MESSAGE);
            validacion = false;
            return validacion;
        }else {
            return validacion;
        }
    }
    private void guardarAltaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarAltaBtnActionPerformed
    inventarioBtn.setEnabled(true);
    modificarBtn.setEnabled(false);
    darDeAltaBtn.setEnabled(true);
    String Numeral,Sub_cat,Nombre,Descripcion,marca,modelo,no_serie,Color,placa,motor,Fecha_compra,No_Factura,
           observaciones,km,km_max;
    int status,clasificacion,cantidad,cantidad_min;
    
    double importe;
    
    status = comboStatus.getSelectedIndex()+1;
    clasificacion = comboClas.getSelectedIndex()+1;
    //ID = Integer.valueOf(idAltaField.getText());
    Numeral = numeralAltaField.getText();
    Sub_cat = subcatAltaField.getText();
    Nombre = nombreAltaField.getText();
    Color = colorAltaField.getText();
    Descripcion = descAltaField.getText();
    Fecha_compra = getFecha();
    No_Factura = noFacAltaField.getText();
    importe = Double.valueOf(importeAltaField.getText());
    marca = marcaAltaField.getText();
    modelo = modeloAltaField.getText();
    no_serie = noSerieAltaField.getText();
    cantidad = Integer.valueOf(cantidadAltaField.getText());
    observaciones = obsAltaField.getText();
    cantidad_min = Integer.valueOf(cantMinAltaField.getText());
    placa = placaAltaField.getText();
    km = kilomAltaField.getText();
    motor = motorAltaField.getText();
    km_max = kilomMaxAltaField.getText();
    
    //validacion(Numeral, Sub_cat, Nombre, Color, Descripcion, Fecha_compra, No_Factura, importe, marca, modelo,
      //         no_serie, cantidad, observaciones, cantidad_min, placa, km, motor, km_max);
    
    //if(validacion == true){
         try {
             PreparedStatement pst;
            System.out.println("Previo a conexion..."); 
            con = new conexion();
            if(comboClas.getSelectedIndex()==7){
                if(accion.equals("Insertar")){
                sql= "INSERT INTO productos(con_pro,subcat_pro,nom_pro,des_pro,mar_pro,mod_pro,ser_pro,col_pro,pla_pro,nomot_pro,fechcompra_pro,nofact_pro,imp_pro,obs_pro,stock_pro,stockmin_pro,km_pro,km_ser_pro,status_id_status,clasificacion_id_clas)"+" VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                mensaje="Los datos se han insertado";
                borrarCampos();
            }
            
            if((accion.equals("Modificar"))){
                System.out.println("Estoy actualizando...");
                sql= "UPDATE productos SET con_pro = ?, subcat_pro = ?, nom_pro = ?,des_pro = ?,mar_pro = ?, mod_pro = ?,ser_pro = ?,col_pro = ?,pla_pro = ?,nomot_pro = ?,fechcompra_pro = ?,nofact_pro = ?,imp_pro = ?,obs_pro = ?, stock_pro = ?, stockmin_pro = ?, km_pro = ?,km_ser_pro = ?,status_id_status = ?,clasificacion_id_clas = ? WHERE idproductos = "+id_actualizar;
                mensaje="Los datos se han actualizado";
            }
            pst=con.conectar.prepareStatement(sql);
            pst.setString(1, Numeral);
            pst.setString(2, Sub_cat);
            pst.setString(3, Nombre);
            pst.setString(4, Descripcion);
            pst.setString(5, marca);
            pst.setString(6, modelo);
            pst.setString(7, no_serie);
            pst.setString(8, Color);
            pst.setString(9, placa);
            pst.setString(10, motor);
            pst.setString(11, Fecha_compra);
            pst.setString(12, No_Factura);
            pst.setDouble(13, importe);
            pst.setString(14, observaciones);
            pst.setInt(15, cantidad);
            pst.setInt(16, cantidad_min);
            pst.setString(17, km);
            pst.setString(18, km_max);
            pst.setInt(19, status);
            pst.setInt(20, clasificacion);
            }
            else{
            if(accion.equals("Insertar")){
                sql= "INSERT INTO productos(con_pro,subcat_pro,nom_pro,des_pro,mar_pro,mod_pro,ser_pro,col_pro,fechcompra_pro,nofact_pro,imp_pro,obs_pro,stock_pro,stockmin_pro,status_id_status,clasificacion_id_clas)"+" VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                mensaje="Los datos se han insertado";
                borrarCampos();
            }
            
            if((accion.equals("Modificar"))){
                System.out.println("Estoy actualizando...");
                sql= "UPDATE productos SET con_pro = ?, subcat_pro = ?, nom_pro = ?,des_pro = ?,mar_pro = ?, mod_pro = ?,ser_pro = ?,col_pro = ?,fechcompra_pro = ?,nofact_pro = ?,imp_pro = ?,obs_pro = ?, stock_pro = ?, stockmin_pro = ?, status_id_status = ?,clasificacion_id_clas = ? WHERE idproductos = "+id_actualizar;
                mensaje="Los datos se han actualizado";
            }
            pst=con.conectar.prepareStatement(sql);
            pst.setString(1, Numeral);
            pst.setString(2, Sub_cat);
            pst.setString(3, Nombre);
            pst.setString(4, Descripcion);
            pst.setString(5, marca);
            pst.setString(6, modelo);
            pst.setString(7, no_serie);
            pst.setString(8, Color);
            pst.setString(9, Fecha_compra);
            pst.setString(10, No_Factura);
            pst.setDouble(11, importe);
            pst.setString(12, observaciones);
            pst.setInt(13, cantidad);
            pst.setInt(14, cantidad_min);
            pst.setInt(15, status);
            pst.setInt(16, clasificacion);
            }
            
           
            int n=pst.executeUpdate();
            borrarCampos();
            System.out.println("Valor n= "+n);
            if(n>0){
                JOptionPane.showMessageDialog(null, mensaje);
                primeraCarga();
            if(accion == "Modificar"){
                panelAlta.setVisible(false);
                panelInventario.setVisible(true);
                comboClas.setSelectedIndex(0);
                comboStatus.setSelectedIndex(0);
            }
                
            }
        } catch (SQLException ex) {
           System.out.println("Entró a catch...");
           JOptionPane.showMessageDialog(null, ex);
        }
   // }
  //  borrarCampos();
    }//GEN-LAST:event_guardarAltaBtnActionPerformed

    private void comboClasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboClasActionPerformed
        if(comboClas.getSelectedIndex()!=7){
            panelAuto.setVisible(false);
        }else if(comboClas.getSelectedIndex()==7){ 
            panelAuto.setVisible(true);
        }
    }//GEN-LAST:event_comboClasActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
    borrarCampos();
    }//GEN-LAST:event_CancelarActionPerformed

    private void tablaInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaInventarioMouseClicked
        int filas;
        String Id;
        accion="Modificar";
        filas= tablaInventario.getSelectedRow();
        Id=(String)modelo.getValueAt(filas,0);
        System.out.println("Valor ID= "+Id);
        id_actualizar = Id;
        cargarDatos(Id);
        modificarBtn.setEnabled(true);
        darDeBajaBtn.setEnabled(true);
    }//GEN-LAST:event_tablaInventarioMouseClicked

    private void buscarFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarFieldKeyReleased
        cargarTabla(buscarField.getText());
    }//GEN-LAST:event_buscarFieldKeyReleased

    private void darDeBajaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darDeBajaBtnActionPerformed
        if(JOptionPane.YES_NO_OPTION==JOptionPane.showConfirmDialog(null,"¿Desea eliminar este producto? ","Eliminar productos",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)){
            System.out.println("Previo a mensaje y deshabilitacion");
            String id=idAltaField.getText();
            mensaje="Producto eliminado";
        
            try {
                con = new conexion();
                con.Eliminar("productos", "idproductos", id);
                JOptionPane.showMessageDialog(null, mensaje);
                primeraCarga();
                JOptionPane.showMessageDialog(null, "se cargó tabla correctamente");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        modificarBtn.setEnabled(false);
        darDeBajaBtn.setEnabled(false);
    }//GEN-LAST:event_darDeBajaBtnActionPerformed

    private void subcatAltaFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subcatAltaFieldKeyPressed
        char c = evt.getKeyChar();
    }//GEN-LAST:event_subcatAltaFieldKeyPressed

    private void noFacAltaFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noFacAltaFieldKeyTyped
char c = evt.getKeyChar();
if(c<'0' || c>'9') evt.consume();// TODO add your handling code here:
    }//GEN-LAST:event_noFacAltaFieldKeyTyped

    private void importeAltaFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_importeAltaFieldKeyTyped
char c = evt.getKeyChar();
if(c<'0' || c>'9') evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_importeAltaFieldKeyTyped

    private void cantidadAltaFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadAltaFieldKeyTyped
char c = evt.getKeyChar();
if(c<'0' || c>'9') evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadAltaFieldKeyTyped

    private void cantMinAltaFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantMinAltaFieldKeyTyped
char c = evt.getKeyChar();
if(c<'0' || c>'9') evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_cantMinAltaFieldKeyTyped

    private void kilomAltaFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kilomAltaFieldKeyTyped
char c = evt.getKeyChar();
if(c<'0' || c>'9') evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_kilomAltaFieldKeyTyped

    private void kilomMaxAltaFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kilomMaxAltaFieldKeyTyped
char c = evt.getKeyChar();
if(c<'0' || c>'9') evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_kilomMaxAltaFieldKeyTyped

    private void motorAltaFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_motorAltaFieldKeyTyped
char c = evt.getKeyChar();
if(c<'0' || c>'9') evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_motorAltaFieldKeyTyped

    private void nombreAltaFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreAltaFieldKeyTyped
char c = evt.getKeyChar();
if((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) evt.consume();
    }//GEN-LAST:event_nombreAltaFieldKeyTyped

    private void colorAltaFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_colorAltaFieldKeyTyped
char c = evt.getKeyChar();
if((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_colorAltaFieldKeyTyped

    private void marcaAltaFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marcaAltaFieldKeyTyped
char c = evt.getKeyChar();
if((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_marcaAltaFieldKeyTyped

    private void noSerieAltaFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noSerieAltaFieldKeyTyped
char c = evt.getKeyChar();
//c.toUpperCase();// TODO add your handling code here:
    }//GEN-LAST:event_noSerieAltaFieldKeyTyped

    public void cargarTabla(String valor){
        String[] titulos={"ID","clave","Nombre","Marca","Serie","Color","Placas","Stock"};

        String[] registros= new String[8];
        modelo = new DefaultTableModel(null,titulos);
        try {
            //Mostrar registros en la tabla
            con = new conexion();
            ResultSet consulta= con.Consultar1("productos", "nom_pro", valor);
            while(consulta.next()){
                registros[0] = consulta.getString("idproductos");
                registros[1] = consulta.getString("clave");
                registros[2] = consulta.getString("nom_pro");
                registros[3] = consulta.getString("mar_pro");
                registros[4] = consulta.getString("ser_pro");
                registros[5] = consulta.getString("col_pro");
                registros[6] = consulta.getString("placas");
                registros[7] = consulta.getString("stock_pro");
                modelo.addRow(registros);               
            }
            //Mostrar titulos de la tabla
            tablaInventario.setModel(modelo);
            
        } catch (SQLException ex) {    
            JOptionPane.showMessageDialog(null,ex);
        }
    }
    
    private void cargarDatos(String Id){
        try {
            con = new conexion();
            ResultSet consulta = con.Consultar2("productos", "idproductos", Id);
            //Recorre registros para mostrarlos
            while(consulta.next()){
                idAltaField.setText(consulta.getString("idproductos"));
                numeralAltaField.setText(consulta.getString("con_pro"));
                subcatAltaField.setText(consulta.getString("subcat_pro"));
                nombreAltaField.setText(consulta.getString("nom_pro"));
                descAltaField.setText(consulta.getString("des_pro"));
                marcaAltaField.setText(consulta.getString("mar_pro"));
                modeloAltaField.setText(consulta.getString("mod_pro"));
                noSerieAltaField.setText(consulta.getString("ser_pro"));
                colorAltaField.setText(consulta.getString("col_pro"));
                placaAltaField.setText(consulta.getString("pla_pro"));
                motorAltaField.setText(consulta.getString("nomot_pro"));
                jDateChooser1.setDate(consulta.getDate("fechcompra_pro"));
                noFacAltaField.setText(consulta.getString("nofact_pro"));
                importeAltaField.setText(consulta.getString("imp_pro"));
                obsAltaField.setText(consulta.getString("obs_pro"));
                cantidadAltaField.setText(consulta.getString("stock_pro"));
                cantMinAltaField.setText(consulta.getString("stockmin_pro"));
                kilomAltaField.setText(consulta.getString("km_pro"));
                kilomMaxAltaField.setText(consulta.getString("km_ser_pro"));
                comboStatus.setSelectedIndex(consulta.getInt("status_id_status")-1);
                comboClas.setSelectedIndex(consulta.getInt("clasificacion_id_clas")-1);
            }
            
        } catch (SQLException ex) {}
    }
    
    private String getFecha(){
       String a,m,d,fecha;
       
       a=""+jDateChooser1.getCalendar().get(Calendar.YEAR);
       m=""+jDateChooser1.getCalendar().get(Calendar.MONTH);
       d=""+jDateChooser1.getCalendar().get(Calendar.DAY_OF_MONTH); 
       return fecha=a+"-"+m+"-"+d;
    }
    
    private void cargarNuevoProducto(){
        int id=0,numeral=0;
        try {
            con = new conexion();
            ResultSet consulta = con.ConsultarNuevoID();
            //Recorre registros para mostrarlos
            while(consulta.next()){
                try{
                id = Integer.parseInt(consulta.getString("id"))+1;
                numeral = Integer.parseInt(consulta.getString("numeral"))+1;
                }catch(NumberFormatException e){
                    id = 1;
                    numeral = 1;
                }
            }
           
            idAltaField.setText(""+id);
            if(numeral<10){
            numeralAltaField.setText("000"+numeral);
            }else if(numeral>=10 && numeral<100) numeralAltaField.setText("00"+numeral);
            else if(numeral>=100 && numeral<1000) numeralAltaField.setText("0"+numeral);
            else numeralAltaField.setText(""+numeral);
        } catch (SQLException ex) {}
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraLatera;
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel ID1;
    private javax.swing.JLabel ID2;
    private javax.swing.JPanel areaAcción;
    private javax.swing.JButton atrasBtn;
    private javax.swing.JTextField buscarField;
    private javax.swing.JTextField cantMinAltaField;
    private javax.swing.JTextField cantidadAltaField;
    private javax.swing.JTextField colorAltaField;
    private javax.swing.JComboBox<String> comboClas;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JButton darDeAltaBtn;
    private javax.swing.JButton darDeBajaBtn;
    private javax.swing.JTextArea descAltaField;
    private javax.swing.JButton guardarAltaBtn;
    private javax.swing.JTextField idAltaField;
    private javax.swing.JTextField importeAltaField;
    private javax.swing.JButton inventarioBtn;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField kilomAltaField;
    private javax.swing.JTextField kilomMaxAltaField;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblnumeral;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField marcaAltaField;
    private javax.swing.JTextField modeloAltaField;
    private javax.swing.JButton modificarBtn;
    private javax.swing.JTextField motorAltaField;
    private javax.swing.JTextField noFacAltaField;
    private javax.swing.JTextField noSerieAltaField;
    private javax.swing.JTextField nombreAltaField;
    private javax.swing.JTextField numeralAltaField;
    private javax.swing.JTextArea obsAltaField;
    private javax.swing.JPanel panelAlta;
    private javax.swing.JPanel panelAuto;
    private javax.swing.JPanel panelInventario;
    private javax.swing.JTextField placaAltaField;
    private javax.swing.JTextField subcatAltaField;
    private javax.swing.JTable tablaInventario;
    // End of variables declaration//GEN-END:variables

    private void borrarCampos() {
    idAltaField.setText("");
    numeralAltaField.setText("");
    subcatAltaField.setText("");
    nombreAltaField.setText("");
    colorAltaField.setText("");
    descAltaField.setText("");
    jDateChooser1.setCalendar(new GregorianCalendar());
    noFacAltaField.setText("");
    importeAltaField.setText("");
    marcaAltaField.setText("");
    modeloAltaField.setText("");
    noSerieAltaField.setText("");
    cantidadAltaField.setText("");
    obsAltaField.setText("");
    cantMinAltaField.setText("");
    placaAltaField.setText("");
    kilomAltaField.setText("");
    motorAltaField.setText("");
    kilomMaxAltaField.setText("");
    }
}
