
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Eduardo
 */
public class ventanaInicio extends javax.swing.JFrame {
    
    Connection con = null;
    Statement stmt = null;
    String titulos[] = {"ID","Producto","Marca","Modelo","Serie","Color"};
    String fila[] = new String[6];
    DefaultTableModel modelo;
    
    public ventanaInicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        /*this.setTitle("Inventario");
        
        btProductos.setEnabled(false);
        
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize((int) d.getWidth() , (int) d.getHeight());
        
        jPanel1.setSize(d);
        background.setSize(d);
        ImageIcon imagen = new ImageIcon("C:/GPS/SistemaInventarioIEEN/IEEN/src/Imagenes/backgroundInicial.png");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(background.getWidth(), background.getHeight(), Image.SCALE_DEFAULT));
        background.setIcon(icono);
        this.repaint();
        
        menu.setSize(160, d.height);
        
        ImageIcon imagen2 = new ImageIcon("C:/GPS/SistemaInventarioIEEN/IEEN/src/Imagenes/n2.png");
        Icon icono2 = new ImageIcon(imagen2.getImage().getScaledInstance(logo.getWidth(), logo.getHeight(), Image.SCALE_DEFAULT));
        logo.setIcon(icono2);
        
        this.setResizable(false);
        
        try {
            
            String url = "jdbc:mysql://localhost:3306/inventario";
            String usuario = "root";
            String contraseña = "lalitro19";  
            
               Class.forName("com.mysql.jdbc.Driver").newInstance();
               con = DriverManager.getConnection(url,usuario,contraseña);
               if (con!= null)
                   System.out.println("Se ha establecido una conexion a la base de datos"+"\n"+url);
               
               stmt = con.createStatement();
               ResultSet rs = stmt.executeQuery("select idproductos,nom_pro,mar_pro,mod_pro,ser_pro,col_pro from productos");
               
               modelo = new DefaultTableModel(null,titulos);
            
               while(rs.next()) {
                   
                   fila[0] = rs.getString("idproductos");
                   fila[1] = rs.getString("nom_pro");
                   fila[2] = rs.getString("mar_pro");
                   fila[3] = rs.getString("mod_pro");
                   fila[4] = rs.getString("ser_pro");
                   fila[5] = rs.getString("col_pro");
                   
                   modelo.addRow(fila);     
               }
               datos.setModel(modelo);
               
        }
        catch (Exception e) {
            
            JOptionPane.showMessageDialog(null,"Error al extraer los datos de la tabla");
        }*/

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        solicitudBtn = new javax.swing.JButton();
        inventarioBtn = new javax.swing.JButton();
        cerrarBtn = new javax.swing.JButton();
        usuarioBtn = new javax.swing.JButton();
        notificacionBtn = new javax.swing.JButton();
        viaticosBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(411, 559));
        setPreferredSize(new java.awt.Dimension(411, 585));
        setResizable(false);
        getContentPane().setLayout(null);

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setLayout(null);

        solicitudBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Solicitudes.png"))); // NOI18N
        solicitudBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitudBtnActionPerformed(evt);
            }
        });
        menu.add(solicitudBtn);
        solicitudBtn.setBounds(210, 330, 190, 70);

        inventarioBtn.setBackground(new java.awt.Color(255, 255, 255));
        inventarioBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inventario.png"))); // NOI18N
        inventarioBtn.setBorder(null);
        inventarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioBtnActionPerformed(evt);
            }
        });
        menu.add(inventarioBtn);
        inventarioBtn.setBounds(10, 330, 190, 70);

        cerrarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar Sesión.png"))); // NOI18N
        cerrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarBtnActionPerformed(evt);
            }
        });
        menu.add(cerrarBtn);
        cerrarBtn.setBounds(210, 480, 190, 70);

        usuarioBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuarios.png"))); // NOI18N
        usuarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioBtnActionPerformed(evt);
            }
        });
        menu.add(usuarioBtn);
        usuarioBtn.setBounds(10, 400, 190, 70);

        notificacionBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Notificaciones.png"))); // NOI18N
        notificacionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificacionBtnActionPerformed(evt);
            }
        });
        menu.add(notificacionBtn);
        notificacionBtn.setBounds(210, 400, 190, 70);

        viaticosBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Viáticos.png"))); // NOI18N
        menu.add(viaticosBtn);
        viaticosBtn.setBounds(10, 480, 190, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BackgroundLogin.jpg"))); // NOI18N
        menu.add(jLabel1);
        jLabel1.setBounds(0, 0, 410, 560);

        getContentPane().add(menu);
        menu.setBounds(0, -1, 410, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inventarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioBtnActionPerformed
        new ventanaInventario().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_inventarioBtnActionPerformed

    private void cerrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarBtnActionPerformed
        new loginWindow().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cerrarBtnActionPerformed

    private void notificacionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificacionBtnActionPerformed
        new ventanaNotificaciones().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_notificacionBtnActionPerformed

    private void usuarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioBtnActionPerformed
        new ventanaUsuario().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioBtnActionPerformed

    private void solicitudBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitudBtnActionPerformed
        new ventanaSolicitar().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_solicitudBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarBtn;
    private javax.swing.JButton inventarioBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel menu;
    private javax.swing.JButton notificacionBtn;
    private javax.swing.JButton solicitudBtn;
    private javax.swing.JButton usuarioBtn;
    private javax.swing.JButton viaticosBtn;
    // End of variables declaration//GEN-END:variables
}
